### PR TITLE
Added index.d.ts

### PR DESCRIPTION
**Pull request by LacticWhale**
Typescript... Typescript... Typescript...

### CODE REVIEW

**Comment by LacticWhale** [comment]
I fixed some typos.

**Comment by webpapaya** [comment]
Hello @LacticWhale this is amazing and TS type definitions were on my list for a very long time. I'll have a look on it today evening and give feedback to you.

**Comment by webpapaya** [comment]
@LacticWhale I just started to have a look on the types and really good job so far. As this library has a pretty excessive test suite I would like to reuse the tests to verify the types. I started with the setup on https://github.com/webpapaya/pomeranian-durations/tree/typescript. The process for the first couple of files was:

- `npm run check-types -- --watch`
- rename a .spec.js file to .spec.ts
- change the import to 'pomeranian-durations' instead
- add // @ts-ignore above the hamjest import
  - there is still https://github.com/rluba/hamjest/pull/33
- fix the typescript errors in typings.d.ts

Depending on your time and resources you could continue with the conversion of the specs. Otherwise I would continue this Friday and we should have the TS typings working somewhen the coming weekend. So just let me know if you want to work on this and if you need any assistance with the setup.

**Comment by webpapaya** [comment]
As I didn't get a feedback yet, I'm going to merge this branch and apply my changes in a dedicated PR. Thanks for your support.

**Pull request merged**
